#!/usr/bin/env python3
"""
Source-of-truth question authoring script for Rukhsa (UAE Driving Test).

Run this once (or whenever content changes) to (re)generate the per-category
JSON files under rukhsa/content/bank/. English ("en") and Arabic ("ar") text
is authored by hand below. Other 8 languages are NOT authored here manually -
build_bundle.py fills them with an English fallback + translationStatus:
"pending" marker, so it is always clear which text is a verified translation
and which is a placeholder.

Facts that are commonly cited for the UAE RTA theory test but that we are not
fully confident about (exact fine amounts, exact black-point counts, etc.)
are marked needsVerification: true so they are easy to filter out and check
against the official RTA Light Motor Vehicle Driver's Handbook before this
content is treated as authoritative.
"""
import json
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "content", "bank")

# Each question dict:
#   id, category, subcategory(optional), difficulty(1-3),
#   en: {q, options[4], explanation}, ar: {q, options[4], explanation},
#   answer (index), needsVerification (bool)

BANK = {
"road_signs": [
 dict(id="rs_001", subcategory="mandatory", difficulty=1,
   en=dict(q="A circular blue sign with a white arrow pointing straight up means:",
           options=["You must go straight ahead only","You should avoid going straight","Straight ahead is closed","No entry"],
           explanation="Round blue signs are mandatory instruction signs; a straight arrow means traffic MUST proceed straight ahead. Round signs (not blue) with red borders are prohibitive, and squares/rectangles are usually informatory."),
   ar=dict(q="إشارة دائرية زرقاء بسهم أبيض يشير إلى الأعلى مباشرة تعني:",
           options=["يجب المتابعة مباشرة فقط","يفضل تجنب الاتجاه المستقيم","الطريق المستقيم مغلق","ممنوع الدخول"],
           explanation="الإشارات الدائرية الزرقاء هي إشارات إلزامية؛ السهم المستقيم يعني وجوب المتابعة مباشرة فقط."),
   answer=0),
 dict(id="rs_002", subcategory="mandatory", difficulty=1,
   en=dict(q="A blue circular sign showing a right-turn arrow means:",
           options=["Right turn ahead, proceed with caution","You must turn right only, no other direction allowed","Right turn is prohibited","Give way to traffic from the right"],
           explanation="Blue circular signs are mandatory - they command an action rather than merely warn. An arrow on blue means that is the ONLY direction permitted at that point."),
   ar=dict(q="إشارة دائرية زرقاء تحمل سهماً للانعطاف يميناً تعني:",
           options=["منعطف يمين قادم، كن حذراً","يجب الانعطاف يميناً فقط ولا يسمح باتجاه آخر","الانعطاف يميناً ممنوع","أعط الأولوية للقادمين من اليمين"],
           explanation="الإشارات الزرقاء الدائرية إلزامية، وتعني أن الاتجاه الموضح هو الاتجاه الوحيد المسموح به."),
   answer=1),
 dict(id="rs_003", subcategory="mandatory", difficulty=2,
   en=dict(q="A blue circular sign with a bicycle symbol and no other markings means:",
           options=["Cyclists prohibited","Path reserved for cyclists only","Watch out for cyclists","Cyclists must dismount"],
           explanation="A plain blue circle with only a bicycle icon is a mandatory sign designating a route/path that must be used by cyclists (and only cyclists), similar to a dedicated mandatory cycle path sign."),
   ar=dict(q="إشارة دائرية زرقاء تحمل رمز دراجة هوائية فقط تعني:",
           options=["الدراجات ممنوعة","مسار مخصص للدراجات الهوائية فقط","احذر الدراجات الهوائية","يجب النزول عن الدراجة"],
           explanation="الدائرة الزرقاء مع رمز الدراجة فقط هي إشارة إلزامية تخصص المسار للدراجات الهوائية حصراً."),
   answer=1),
 dict(id="rs_004", subcategory="warning", difficulty=1,
   en=dict(q="A red-bordered triangular sign generally indicates:",
           options=["A mandatory instruction","A warning of a hazard ahead","A prohibition","Distance information"],
           explanation="Triangular signs with a red border are warning signs that alert drivers to a hazard or change in road conditions ahead, such as a curve, crossing, or narrow road."),
   ar=dict(q="الإشارة المثلثة ذات الحافة الحمراء تدل بشكل عام على:",
           options=["تعليمة إلزامية","تحذير من خطر أمامك","منع","معلومات عن المسافة"],
           explanation="الإشارات المثلثة ذات الحافة الحمراء هي إشارات تحذيرية تنبه السائق لخطر أو تغيّر في حالة الطريق أمامه."),
   answer=1),
 dict(id="rs_005", subcategory="warning", difficulty=1,
   en=dict(q="A triangular warning sign showing a camel means:",
           options=["Camel racing track nearby","Camels may cross the road ahead - slow down","Camel market ahead","No entry for camels"],
           explanation="This warning sign is common on UAE desert and inter-emirate roads; it warns that camels or other animals may wander onto the road, so drivers should reduce speed and stay alert, especially at dusk/night."),
   ar=dict(q="إشارة تحذيرية مثلثة تظهر جملاً تعني:",
           options=["مضمار لسباق الهجن قريب","قد تعبر الجمال الطريق أمامك - خفف السرعة","سوق جمال أمامك","ممنوع دخول الجمال"],
           explanation="هذه الإشارة شائعة على الطرق الصحراوية وبين الإمارات، وتحذر من احتمال عبور الجمال أو الحيوانات للطريق، خصوصاً عند الغروب والليل."),
   answer=1),
 dict(id="rs_006", subcategory="warning", difficulty=2,
   en=dict(q="A warning sign showing a curved arrow indicating a sharp bend to the right means you should:",
           options=["Increase speed to clear the bend quickly","Reduce speed in advance and steer carefully through the bend","Stop completely before the bend","Overtake before entering the bend"],
           explanation="Warning signs give advance notice so a driver can adjust speed safely before reaching the hazard; the correct response to a sharp bend warning is to slow down before entering it, not while already in it."),
   ar=dict(q="إشارة تحذيرية تظهر سهماً منحنياً لمنعطف حاد لليمين تعني أنه يجب عليك:",
           options=["زيادة السرعة لتجاوز المنعطف بسرعة","خفض السرعة مسبقاً والانعطاف بحذر","التوقف التام قبل المنعطف","التجاوز قبل الدخول في المنعطف"],
           explanation="الإشارات التحذيرية تعطي إنذاراً مسبقاً لتعديل السرعة؛ الاستجابة الصحيحة هي تخفيف السرعة قبل الدخول في المنعطف."),
   answer=1),
 dict(id="rs_007", subcategory="informatory", difficulty=1,
   en=dict(q="A blue rectangular sign showing a letter 'P' with a number indicates:",
           options=["Police station ahead","Parking with a specified number of available bays or the parking zone number","Petrol station ahead","Speed limit in that zone"],
           explanation="Rectangular blue informatory signs give the driver useful information; a 'P' sign is the standard parking information sign."),
   ar=dict(q="إشارة مستطيلة زرقاء تظهر الحرف 'P' مع رقم تدل على:",
           options=["مركز شرطة أمامك","موقف سيارات (منطقة/عدد الأماكن)","محطة وقود أمامك","حد السرعة في تلك المنطقة"],
           explanation="الإشارات المستطيلة الزرقاء هي إشارات إرشادية تعطي معلومة مفيدة؛ إشارة 'P' هي الإشارة القياسية لمواقف السيارات."),
   answer=1),
 dict(id="rs_008", subcategory="informatory", difficulty=1,
   en=dict(q="A blue sign with a white 'H' typically indicates:",
           options=["Hospital nearby","Highway entrance","Height restriction ahead","Hotel zone"],
           explanation="An 'H' informatory sign points drivers toward the nearest hospital, useful information rather than an instruction or warning."),
   ar=dict(q="إشارة زرقاء بحرف 'H' أبيض تدل عادة على:",
           options=["مستشفى قريب","مدخل طريق سريع","تحديد ارتفاع أمامك","منطقة فنادق"],
           explanation="إشارة 'H' الإرشادية توجه السائق إلى أقرب مستشفى."),
   answer=0),
 dict(id="rs_009", subcategory="directional", difficulty=1,
   en=dict(q="Green rectangular signs with white text on UAE highways generally indicate:",
           options=["Directions to cities and highway destinations","Local street names only","School zones","Temporary construction detours"],
           explanation="On UAE roads, green overhead/roadside signs are directional signs used mainly for inter-city and highway route guidance."),
   ar=dict(q="اللافتات المستطيلة الخضراء ذات النص الأبيض على طرق الإمارات تدل عادة على:",
           options=["اتجاهات إلى المدن ووجهات الطرق السريعة","أسماء الشوارع المحلية فقط","مناطق مدارس","تحويلات مؤقتة بسبب الإنشاءات"],
           explanation="اللافتات الخضراء على طرق الإمارات هي إشارات اتجاهية تُستخدم أساساً لتوجيه حركة المرور بين المدن وعلى الطرق السريعة."),
   answer=0),
 dict(id="rs_010", subcategory="directional", difficulty=2,
   en=dict(q="A blue rectangular directional sign (as opposed to green) is generally used for:",
           options=["Directions within a city/local area rather than an inter-city highway","National highways only","Emergency services only","Off-road tracks"],
           explanation="Blue directional signs are commonly used for local/city destinations, while green ones are used for highways/inter-city destinations - the colour helps drivers judge the type of route at a glance.",
           ),
   ar=dict(q="تُستخدم الإشارة الاتجاهية المستطيلة الزرقاء (بخلاف الخضراء) عادة من أجل:",
           options=["الاتجاهات داخل المدينة/المنطقة المحلية بدلاً من الطرق السريعة بين المدن","الطرق السريعة الوطنية فقط","خدمات الطوارئ فقط","المسارات الوعرة"],
           explanation="تُستخدم الإشارات الزرقاء عادة للوجهات المحلية/داخل المدينة، بينما تُستخدم الخضراء للطرق السريعة بين المدن."),
   answer=0, needsVerification=True),
 dict(id="rs_011", subcategory="mandatory", difficulty=1,
   en=dict(q="A round sign with a red border, red diagonal line, and no other symbol means:",
           options=["No entry for any vehicle in that direction","One-way street","No parking","No overtaking"],
           explanation="A plain red circle with a horizontal red bar (or a full red circle) is the standard 'No Entry' sign, prohibiting vehicles from entering in that direction."),
   ar=dict(q="إشارة دائرية بحافة حمراء وخط أحمر أفقي بدون أي رمز آخر تعني:",
           options=["ممنوع الدخول لأي مركبة في ذلك الاتجاه","طريق باتجاه واحد","ممنوع الوقوف","ممنوع التجاوز"],
           explanation="الدائرة الحمراء ذات الخط الأفقي هي إشارة 'ممنوع الدخول' القياسية."),
   answer=0),
 dict(id="rs_012", subcategory="warning", difficulty=2,
   en=dict(q="A triangular sign showing two children walking is typically placed near:",
           options=["Shopping malls","Schools or areas with frequent pedestrian children crossing","Hospitals","Petrol stations"],
           explanation="This warning sign alerts drivers to slow down and watch for children near schools or play areas, where children may cross unexpectedly."),
   ar=dict(q="إشارة مثلثة تظهر طفلين يمشيان توضع عادة بالقرب من:",
           options=["مراكز التسوق","المدارس أو المناطق التي يكثر فيها عبور الأطفال","المستشفيات","محطات الوقود"],
           explanation="هذه الإشارة التحذيرية تنبه السائق لتخفيف السرعة والحذر من الأطفال بالقرب من المدارس."),
   answer=1),
],
"traffic_rules_row": [
 dict(id="tr_001", difficulty=1,
   en=dict(q="At an intersection with no signs or signals, and two vehicles arrive at the same time from different roads, who has the right of way?",
           options=["The vehicle on the right","The vehicle on the left","The faster vehicle","Whoever honks first"],
           explanation="At an uncontrolled intersection, the general right-of-way rule is to give way to traffic approaching from your right."),
   ar=dict(q="عند تقاطع بدون إشارات وصل مركبتان في نفس الوقت من طريقين مختلفين، لمن الأولوية؟",
           options=["للمركبة القادمة من اليمين","للمركبة القادمة من اليسار","للمركبة الأسرع","لمن يستخدم البوق أولاً"],
           explanation="عند التقاطعات غير المنظمة، القاعدة العامة هي إعطاء الأولوية للمركبة القادمة من اليمين."),
   answer=0),
 dict(id="tr_002", difficulty=1,
   en=dict(q="When an emergency vehicle (ambulance/police) approaches from behind with lights and siren on, you should:",
           options=["Speed up to get out of its way","Stay in your lane and ignore it if you are not blocking it","Move safely to the side and let it pass as soon as possible","Stop immediately wherever you are"],
           explanation="Drivers must give way to emergency vehicles by pulling over safely to the side of the road as soon as it is safe to do so, not by stopping abruptly in the traffic lane or speeding away."),
   ar=dict(q="عند اقتراب مركبة طوارئ (إسعاف/شرطة) من الخلف بأضواء وصفارة، يجب عليك:",
           options=["زيادة السرعة للابتعاد عن طريقها","البقاء في مسارك وتجاهلها إذا لم تكن تعيقها","الانتقال بأمان إلى الجانب والسماح لها بالمرور بأسرع وقت آمن","التوقف فوراً في مكانك"],
           explanation="يجب على السائقين إفساح الطريق لمركبات الطوارئ بالانتقال بأمان إلى جانب الطريق بمجرد أن يكون ذلك آمناً."),
   answer=2),
 dict(id="tr_003", difficulty=2,
   en=dict(q="You want to change lanes on a multi-lane road. You should:",
           options=["Change lane quickly without signalling to avoid being cut off","Signal, check mirrors and blind spot, then change lane when safe","Only check the mirror on the side you are moving to","Flash your headlights and change immediately"],
           explanation="Safe lane changes require signalling your intention early, checking mirrors and the blind spot (which mirrors alone cannot show), and moving only once it is clearly safe."),
   ar=dict(q="تريد تغيير المسار على طريق متعدد المسارات، يجب عليك:",
           options=["تغيير المسار بسرعة دون استخدام الإشارة لتفادي منعك","استخدام الإشارة، فحص المرايا والمنطقة العمياء، ثم تغيير المسار عند الأمان","فحص المرآة الجانبية فقط في الاتجاه الذي تنتقل إليه","وميض الأضواء الأمامية وتغيير المسار فوراً"],
           explanation="التغيير الآمن للمسار يتطلب استخدام إشارة الانعطاف مبكراً، وفحص المرايا والمنطقة العمياء قبل التحرك."),
   answer=1),
 dict(id="tr_004", difficulty=1,
   en=dict(q="A solid red traffic light means:",
           options=["Slow down and proceed with caution","Stop completely and wait","Stop only if turning left","Proceed if the road is clear"],
           explanation="A solid red light requires a complete stop before the stop line; you may only proceed once the light turns green (except where a specific green arrow permits a filter turn)."),
   ar=dict(q="الضوء الأحمر الثابت في إشارة المرور يعني:",
           options=["خفف السرعة وتابع بحذر","توقف تماماً وانتظر","توقف فقط عند الانعطاف يساراً","تابع القيادة إذا كان الطريق خالياً"],
           explanation="الضوء الأحمر الثابت يستوجب التوقف التام قبل خط التوقف، ولا يجوز المتابعة إلا عند تحول الإشارة إلى الأخضر."),
   answer=1),
 dict(id="tr_005", difficulty=2,
   en=dict(q="A flashing amber traffic light at a junction means:",
           options=["The signal is broken - ignore it","Proceed with caution, giving way as necessary; treat it like an uncontrolled junction","Stop and wait for it to turn green","It applies only to pedestrians"],
           explanation="A flashing amber light indicates drivers may proceed but must do so with caution and give way appropriately, similar to an uncontrolled intersection."),
   ar=dict(q="الضوء الكهرماني الوامض عند تقاطع يعني:",
           options=["الإشارة معطلة - تجاهلها","تابع بحذر مع إعطاء الأولوية عند الحاجة، وكأنه تقاطع غير منظم","توقف وانتظر حتى يتحول للأخضر","تخص المشاة فقط"],
           explanation="الضوء الكهرماني الوامض يعني إمكانية المتابعة مع الحذر الشديد وإعطاء الأولوية كما لو كان تقاطعاً غير منظم."),
   answer=1),
 dict(id="tr_006", difficulty=1,
   en=dict(q="When you see a pedestrian waiting at a zebra crossing with no traffic signal, you should:",
           options=["Continue driving, pedestrians must wait for a gap","Slow down and stop to let the pedestrian cross safely","Sound your horn so they wait","Speed up before they step onto the crossing"],
           explanation="At a marked pedestrian (zebra) crossing without signals, drivers must give way and stop to allow waiting pedestrians to cross safely."),
   ar=dict(q="عند رؤية أحد المشاة ينتظر عند ممر مشاة بدون إشارة مرور، يجب عليك:",
           options=["متابعة القيادة، على المشاة الانتظار حتى تفرغ الطريق","التباطؤ والتوقف للسماح للمشاة بالعبور بأمان","استخدام البوق ليبقوا منتظرين","زيادة السرعة قبل أن يخطو على الممر"],
           explanation="عند ممر المشاة غير المزود بإشارة، يجب على السائق التوقف وإعطاء الأولوية للمشاة."),
   answer=1),
 dict(id="tr_007", difficulty=2,
   en=dict(q="You are turning left at a junction and there is oncoming traffic going straight. Who has priority?",
           options=["You, because you signalled first","The oncoming straight-moving traffic","Whoever is faster","Both proceed together"],
           explanation="A vehicle turning across the path of oncoming traffic must give way to vehicles coming from the opposite direction that are travelling straight through the junction."),
   ar=dict(q="أنت تنعطف يساراً عند تقاطع وهناك حركة مرور قادمة باتجاه مستقيم، لمن الأولوية؟",
           options=["لك أنت لأنك استخدمت الإشارة أولاً","للمركبات القادمة بشكل مستقيم من الاتجاه المقابل","لمن هو أسرع","يتابع الطرفان معاً"],
           explanation="المركبة التي تنعطف عبر مسار حركة المرور القادمة يجب أن تعطي الأولوية للمركبات المستقيمة القادمة من الاتجاه المقابل."),
   answer=1),
 dict(id="tr_008", difficulty=1,
   en=dict(q="Before overtaking another vehicle, you must first:",
           options=["Sound your horn and pull out immediately","Check mirrors and blind spot, signal, and ensure the road ahead is clear for a safe overtake","Flash your headlights only","Overtake only if the other vehicle is very slow"],
           explanation="A safe overtake requires checking for oncoming traffic and a clear gap, checking mirrors/blind spot, and signalling before committing to the manoeuvre."),
   ar=dict(q="قبل تجاوز مركبة أخرى، يجب عليك أولاً:",
           options=["استخدام البوق والخروج فوراً","فحص المرايا والمنطقة العمياء، استخدام الإشارة، والتأكد من خلو الطريق أمامك للتجاوز الآمن","وميض الأضواء الأمامية فقط","التجاوز فقط إذا كانت المركبة الأخرى بطيئة جداً"],
           explanation="التجاوز الآمن يتطلب التأكد من خلو الطريق من حركة مقابلة، وفحص المرايا والمنطقة العمياء، واستخدام الإشارة قبل التنفيذ."),
   answer=1),
 dict(id="tr_009", difficulty=2,
   en=dict(q="At a T-junction, traffic on the through road (the top of the T) generally has right of way over traffic:",
           options=["Joining from the terminating road (the stem of the T)","Coming from any direction equally","Turning right only","None of the traffic has priority"],
           explanation="At a T-junction, vehicles on the continuous through road normally have priority over vehicles emerging from the road that ends at the junction."),
   ar=dict(q="عند تقاطع على شكل حرف T، تكون الأولوية عموماً لحركة المرور على الطريق المستمر مقارنة بحركة المرور:",
           options=["القادمة من الطريق المنتهي عند التقاطع","القادمة من أي اتجاه بالتساوي","المنعطفة يميناً فقط","لا أولوية لأي طرف"],
           explanation="عند تقاطع T، تكون الأولوية عادة للمركبات على الطريق المستمر مقارنة بالمركبات الخارجة من الطريق المنتهي عند التقاطع."),
   answer=0),
],
"speed_limits": [
 dict(id="sp_001", difficulty=1,
   en=dict(q="Speed limits displayed on UAE road signs are:",
           options=["Recommendations that can be exceeded slightly if traffic is light","Maximum legal speeds for that stretch of road under normal conditions","Minimum speeds required at all times","Only applicable to trucks and buses"],
           explanation="A posted speed limit sign shows the maximum speed permitted under normal conditions; drivers must reduce speed further in poor weather, heavy traffic, or low visibility."),
   ar=dict(q="حدود السرعة المعروضة على لافتات الطرق في الإمارات هي:",
           options=["توصيات يمكن تجاوزها قليلاً عند خفة الحركة المرورية","أقصى سرعة قانونية مسموح بها على ذلك الجزء من الطريق في الظروف العادية","الحد الأدنى المطلوب للسرعة في كل الأوقات","تنطبق فقط على الشاحنات والحافلات"],
           explanation="لافتة حد السرعة تمثل الحد الأقصى المسموح به في الظروف العادية، ويجب تخفيف السرعة أكثر في الأحوال الجوية السيئة أو الازدحام أو ضعف الرؤية."),
   answer=1),
 dict(id="sp_002", difficulty=2,
   en=dict(q="Many UAE highways use a 'speed buffer' or grace margin above the posted limit before a radar-based fine is triggered. As a driver you should:",
           options=["Always drive at the posted limit plus the buffer, since it is effectively allowed","Treat the posted limit as the limit to respect, since the buffer is a tolerance, not an entitlement","Ignore posted limits on highways entirely","Only worry about limits near police checkpoints"],
           explanation="Speed buffers exist as a technical tolerance for radar/speedometer variance, not as an officially sanctioned higher limit. Safe and lawful driving means aiming to stay at or under the posted limit itself.",
           ),
   ar=dict(q="تستخدم كثير من الطرق السريعة في الإمارات هامش سرعة (تفاوت) قبل تفعيل مخالفة الرادار، ماذا يجب أن يفعل السائق؟",
           options=["القيادة دائماً بالحد المسموح زائد الهامش لأنه مسموح فعلياً","اعتبار الحد المعلن هو الحد الواجب الالتزام به لأن الهامش تفاوت تقني وليس حقاً مكتسباً","تجاهل الحدود المعلنة على الطرق السريعة تماماً","الانتباه للحدود فقط بالقرب من نقاط تفتيش الشرطة"],
           explanation="هامش السرعة هو تفاوت تقني للرادار وليس حداً رسمياً أعلى؛ القيادة الآمنة والقانونية تعني الالتزام بالحد المعلن نفسه."),
   answer=1, needsVerification=True),
 dict(id="sp_003", difficulty=1,
   en=dict(q="In residential areas and near schools, speed limits are generally:",
           options=["Higher than main roads to keep traffic flowing","Lower than main roads to protect pedestrians, especially children","The same as highways","Not enforced"],
           explanation="Residential and school zones have lower speed limits because of the higher risk of pedestrians, especially children, entering the roadway unexpectedly."),
   ar=dict(q="في المناطق السكنية وبالقرب من المدارس، تكون حدود السرعة عادة:",
           options=["أعلى من الطرق الرئيسية لتسريع الحركة","أقل من الطرق الرئيسية لحماية المشاة وخاصة الأطفال","مماثلة للطرق السريعة","غير مطبقة"],
           explanation="تكون حدود السرعة في المناطق السكنية ومناطق المدارس أقل بسبب ارتفاع خطر عبور المشاة وخاصة الأطفال بشكل مفاجئ."),
   answer=1),
 dict(id="sp_004", difficulty=2,
   en=dict(q="Driving significantly above the posted speed limit (a major overspeeding violation) in the UAE can result in:",
           options=["A verbal warning only","A fine, black points, and possibly vehicle impoundment for extreme cases","No consequence if no accident occurs","A same-day licence suspension only for tourists"],
           explanation="Serious speeding violations are treated severely under UAE traffic law and can carry heavy fines, black points on the licence, and impoundment of the vehicle for extreme speeds; exact thresholds and amounts should be checked against the official RTA/MOI schedule.",
           ),
   ar=dict(q="القيادة بسرعة أعلى بكثير من الحد المسموح (مخالفة سرعة جسيمة) في الإمارات يمكن أن تؤدي إلى:",
           options=["تحذير شفهي فقط","غرامة ونقاط مرورية وربما حجز المركبة في الحالات القصوى","لا عواقب إذا لم يقع حادث","إيقاف الرخصة لليوم نفسه للسياح فقط"],
           explanation="تُعامل مخالفات السرعة الجسيمة بصرامة ويمكن أن تشمل غرامات كبيرة ونقاطاً مرورية وحجز المركبة في الحالات القصوى؛ يجب التحقق من الأرقام الدقيقة من الجدول الرسمي لهيئة الطرق والمواصلات ووزارة الداخلية."),
   answer=1, needsVerification=True),
 dict(id="sp_005", difficulty=1,
   en=dict(q="In foggy or heavy rain conditions, a driver should:",
           options=["Maintain the posted speed limit regardless of visibility","Reduce speed below the posted limit and increase following distance","Drive with hazard lights on at normal speed","Speed up to leave the poor-visibility zone quickly"],
           explanation="Posted limits assume normal conditions; in fog, heavy rain, or dust, drivers must reduce speed and increase the following distance to compensate for lower visibility and grip."),
   ar=dict(q="في حالة الضباب أو الأمطار الغزيرة، يجب على السائق:",
           options=["الحفاظ على حد السرعة المعلن بغض النظر عن الرؤية","تخفيف السرعة عن الحد المعلن وزيادة مسافة التتبع","القيادة بأضواء التحذير مع سرعة عادية","زيادة السرعة للخروج من منطقة ضعف الرؤية بسرعة"],
           explanation="الحدود المعلنة تفترض ظروفاً طبيعية؛ في الضباب أو الأمطار الغزيرة أو الغبار يجب تخفيف السرعة وزيادة مسافة التتبع."),
   answer=1),
],
"fines_penalty": [
 dict(id="fp_001", difficulty=1,
   en=dict(q="Accumulating a certain number of black points within a set period in the UAE can lead to:",
           options=["No effect on your licence","Licence suspension for a period determined by traffic authorities","Automatic cancellation of vehicle registration only","A discount on future fines"],
           explanation="Black points are added to a driver's record for various violations; reaching a threshold within a given period can lead to licence suspension. Exact point thresholds and durations vary and should be verified against the current official schedule.",
           ),
   ar=dict(q="تراكم عدد معين من النقاط المرورية خلال فترة محددة في الإمارات يمكن أن يؤدي إلى:",
           options=["لا يوجد تأثير على الرخصة","إيقاف الرخصة لفترة تحددها الجهات المرورية","إلغاء تسجيل المركبة تلقائياً فقط","خصم على الغرامات المستقبلية"],
           explanation="تُضاف النقاط المرورية لسجل السائق عند ارتكاب مخالفات مختلفة، وبلوغ حد معين خلال فترة محددة قد يؤدي إلى إيقاف الرخصة؛ يجب التحقق من الأرقام الدقيقة من الجدول الرسمي الحالي."),
   answer=1, needsVerification=True),
 dict(id="fp_002", difficulty=1,
   en=dict(q="Using a mobile phone by hand while driving (not hands-free) is:",
           options=["Allowed if stopped at a red light","A traffic violation that carries a fine and black points","Only illegal on highways","Allowed for making emergency calls only"],
           explanation="Handheld mobile phone use while driving, including when temporarily stationary in traffic, is a common and enforced violation across UAE traffic law, since it counts as a driving distraction."),
   ar=dict(q="استخدام الهاتف المحمول باليد أثناء القيادة (بدون نظام تحدث دون استخدام اليدين) يُعد:",
           options=["مسموحاً عند التوقف بإشارة حمراء","مخالفة مرورية تستوجب غرامة ونقاطاً مرورية","غير قانوني فقط على الطرق السريعة","مسموحاً فقط لإجراء مكالمات الطوارئ"],
           explanation="استخدام الهاتف باليد أثناء القيادة، بما في ذلك أثناء التوقف المؤقت في الزحام، مخالفة شائعة يعاقب عليها القانون المروري في الإمارات."),
   answer=1),
 dict(id="fp_003", difficulty=1,
   en=dict(q="Tailgating (driving too close to the vehicle in front) is treated as:",
           options=["A minor issue with no fine","A traffic violation because it reduces your reaction time and safety margin","Only a problem on wet roads","Something only trucks need to worry about"],
           explanation="Tailgating is a recognised and fined violation because it removes the safety gap needed to react to sudden braking, increasing collision risk."),
   ar=dict(q="القيادة اللاصقة (الاقتراب الزائد من المركبة الأمامية) تُعامل على أنها:",
           options=["مشكلة بسيطة بدون غرامة","مخالفة مرورية لأنها تقلل وقت رد الفعل وهامش الأمان","مشكلة فقط على الطرق المبللة","تهم الشاحنات فقط"],
           explanation="القيادة اللاصقة مخالفة معترف بها ويعاقب عليها لأنها تلغي مسافة الأمان اللازمة للتفاعل مع الفرملة المفاجئة."),
   answer=1),
 dict(id="fp_004", difficulty=2,
   en=dict(q="If you disagree with a traffic fine issued in the UAE, you can generally:",
           options=["Simply refuse to pay it with no consequence","Submit an official objection/appeal through the relevant traffic authority channel","Only contest it in a foreign court","Nothing can be done once issued"],
           explanation="UAE traffic authorities (such as Dubai's RTA/Police smart services) provide an official process to object to or appeal a fine; ignoring it does not remove the fine and can add further penalties.",
           ),
   ar=dict(q="إذا كنت لا توافق على مخالفة مرورية صدرت في الإمارات، يمكنك عموماً:",
           options=["رفض الدفع ببساطة دون أي عواقب","تقديم اعتراض/تظلم رسمي عبر القناة المخصصة لدى الجهة المرورية المعنية","الاعتراض فقط أمام محكمة أجنبية","لا يمكن فعل أي شيء بعد صدورها"],
           explanation="توفر الجهات المرورية في الإمارات (مثل هيئة الطرق والمواصلات وشرطة دبي) قنوات رسمية لتقديم اعتراض على المخالفة."),
   answer=1, needsVerification=True),
 dict(id="fp_005", difficulty=1,
   en=dict(q="Jumping a red light in the UAE is generally treated as:",
           options=["A minor issue similar to a parking fine","A serious violation carrying a heavy fine and black points due to high collision risk","Only enforced at night","Only relevant for commercial drivers"],
           explanation="Running a red light is one of the more heavily penalised violations because of the high risk of severe collisions at intersections."),
   ar=dict(q="تجاوز الإشارة الحمراء في الإمارات يُعامل عموماً على أنه:",
           options=["مشكلة بسيطة مشابهة لمخالفة وقوف","مخالفة جسيمة تستوجب غرامة كبيرة ونقاطاً مرورية بسبب ارتفاع خطر التصادم","تُطبق ليلاً فقط","تخص السائقين التجاريين فقط"],
           explanation="تجاوز الإشارة الحمراء من أكثر المخالفات التي يُعاقب عليها بشدة بسبب ارتفاع خطر وقوع تصادمات خطيرة عند التقاطعات."),
   answer=1, needsVerification=True),
],
"highway_lane": [
 dict(id="hl_001", difficulty=1,
   en=dict(q="On a multi-lane highway, the leftmost (fast) lane is generally intended for:",
           options=["Slow-moving and heavy vehicles","Overtaking and faster-moving traffic, not for continuous cruising","Parking in emergencies only","Buses and taxis exclusively"],
           explanation="The leftmost lane on UAE highways is typically an overtaking lane; drivers should return to a right-hand lane after overtaking rather than staying in it continuously."),
   ar=dict(q="على الطريق السريع متعدد المسارات، يُخصص المسار الأيسر (السريع) عموماً من أجل:",
           options=["المركبات البطيئة والثقيلة","التجاوز وحركة المرور الأسرع، وليس للسير المستمر فيه","الوقوف في حالات الطوارئ فقط","الحافلات وسيارات الأجرة حصراً"],
           explanation="المسار الأيسر على الطرق السريعة في الإمارات هو عادة مسار للتجاوز؛ يجب على السائق العودة إلى مسار أيمن بعد التجاوز بدلاً من البقاء فيه باستمرار."),
   answer=1),
 dict(id="hl_002", difficulty=1,
   en=dict(q="Heavy trucks on UAE highways are generally required to:",
           options=["Use any lane freely like other vehicles","Keep to the designated right-hand lane(s) unless overtaking","Always use the leftmost lane for stability","Travel only at night"],
           explanation="Heavy vehicles are generally restricted to the right-hand lanes on multi-lane highways to keep faster lanes clear for overtaking traffic, improving overall traffic flow and safety."),
   ar=dict(q="يُطلب من الشاحنات الثقيلة على الطرق السريعة في الإمارات عموماً:",
           options=["استخدام أي مسار بحرية مثل باقي المركبات","الالتزام بالمسار (المسارات) اليمنى المخصصة إلا عند التجاوز","استخدام المسار الأيسر دائماً لثباتها","التنقل ليلاً فقط"],
           explanation="تُقيَّد المركبات الثقيلة عموماً بالمسارات اليمنى على الطرق متعددة المسارات لإبقاء المسارات الأسرع خالية لحركة التجاوز."),
   answer=1),
 dict(id="hl_003", difficulty=2,
   en=dict(q="Sudden, unnecessary lane changes ('weaving') between multiple lanes in heavy/fast traffic are:",
           options=["A smart way to save time","A dangerous and penalised practice as it greatly increases collision risk","Only risky at night","Legal as long as you signal each time"],
           explanation="Weaving through traffic increases the risk of side collisions and reduces predictability for other drivers; it is treated as a serious violation on UAE highways."),
   ar=dict(q="تغيير المسارات المفاجئ وغير الضروري (التعرج) بين عدة مسارات في حركة مرور كثيفة/سريعة يُعد:",
           options=["طريقة ذكية لتوفير الوقت","ممارسة خطرة ويعاقب عليها لأنها تزيد كثيراً من خطر التصادم","خطراً ليلاً فقط","قانونياً طالما تم استخدام الإشارة في كل مرة"],
           explanation="التعرج بين المسارات يزيد من خطر التصادمات الجانبية ويقلل من قابلية توقع تصرفاتك من قبل السائقين الآخرين."),
   answer=1),
 dict(id="hl_004", difficulty=1,
   en=dict(q="The hard shoulder (emergency lane) on a highway should be used for:",
           options=["Regular driving when the highway is busy","Genuine emergencies and breakdowns only","Overtaking slow trucks","A shortcut to skip queues near exits"],
           explanation="The hard shoulder is reserved for emergencies, breakdowns, and use by emergency/service vehicles; using it for normal driving or to bypass congestion is prohibited and dangerous."),
   ar=dict(q="يجب استخدام الكتف الصلب (مسار الطوارئ) على الطريق السريع من أجل:",
           options=["القيادة العادية عند ازدحام الطريق","حالات الطوارئ والأعطال الحقيقية فقط","تجاوز الشاحنات البطيئة","اختصار الطابور بالقرب من المخارج"],
           explanation="الكتف الصلب مخصص لحالات الطوارئ والأعطال ومركبات الطوارئ/الخدمة؛ استخدامه للقيادة العادية أو لتجاوز الازدحام ممنوع وخطير."),
   answer=1),
 dict(id="hl_005", difficulty=2,
   en=dict(q="When merging onto a highway from an on-ramp, you should:",
           options=["Stop at the end of the ramp and wait for a large gap","Match the speed of highway traffic and merge smoothly into a safe gap","Force your way in since merging traffic has priority","Merge only from the leftmost lane"],
           explanation="Safe merging means accelerating on the ramp to match the flow of highway traffic and moving into a suitable gap smoothly, rather than stopping unnecessarily or forcing entry."),
   ar=dict(q="عند الاندماج في طريق سريع من منحدر دخول، يجب عليك:",
           options=["التوقف في نهاية المنحدر وانتظار فجوة كبيرة","مطابقة سرعة حركة المرور على الطريق السريع والاندماج بسلاسة في فجوة آمنة","فرض الدخول لأن للمركبة المندمجة الأولوية","الاندماج من المسار الأيسر فقط"],
           explanation="الاندماج الآمن يعني تسريع المركبة على المنحدر لمطابقة سرعة حركة المرور والدخول بسلاسة في فجوة مناسبة."),
   answer=1),
],
"roundabouts_intersections": [
 dict(id="ri_001", difficulty=1,
   en=dict(q="When entering a roundabout, you should generally give way to:",
           options=["Traffic already circulating inside the roundabout","Traffic waiting to enter from other approaches","No one, entering traffic has priority","Only buses and emergency vehicles"],
           explanation="The general roundabout rule is to give way to traffic already on the roundabout before entering, checking to your right/left as appropriate to the direction of circulation."),
   ar=dict(q="عند الدخول إلى دوار، يجب عليك عموماً إعطاء الأولوية لـ:",
           options=["المركبات التي تسير بالفعل داخل الدوار","المركبات المنتظرة للدخول من مداخل أخرى","لا أحد، فالأولوية للداخل","الحافلات ومركبات الطوارئ فقط"],
           explanation="القاعدة العامة للدوارات هي إعطاء الأولوية للمركبات السائرة بالفعل داخل الدوار قبل الدخول إليه."),
   answer=0),
 dict(id="ri_002", difficulty=2,
   en=dict(q="If you plan to exit at the first available exit on a roundabout, you should generally position yourself in:",
           options=["The innermost (leftmost) lane on entry","The lane closest to the exit you intend to use, usually the right-hand lane","Any lane, it does not matter","The middle of the roundabout"],
           explanation="To take an early exit safely, a driver should approach and stay in the lane nearest to that exit, avoiding cutting across lanes just before exiting."),
   ar=dict(q="إذا كنت تنوي الخروج من أول مخرج متاح في الدوار، يجب عليك عموماً التموضع في:",
           options=["المسار الداخلي (الأيسر) عند الدخول","المسار الأقرب للمخرج الذي تنوي استخدامه، عادة المسار الأيمن","أي مسار، لا فرق","منتصف الدوار"],
           explanation="للخروج المبكر بأمان، يجب على السائق البقاء في المسار الأقرب لذلك المخرج وتجنب قطع المسارات فجأة قبل الخروج."),
   answer=1),
 dict(id="ri_003", difficulty=2,
   en=dict(q="At a busy intersection controlled by a police officer whose signals conflict with the traffic lights, you must:",
           options=["Follow the traffic lights, as they are automatic and always correct","Follow the police officer's directions, which override the traffic lights","Stop completely and wait for both to agree","Follow whichever is more convenient for your direction"],
           explanation="A traffic police officer's directions take precedence over traffic lights and signs, since the officer can respond to real-time conditions the automated signal cannot."),
   ar=dict(q="عند تقاطع مزدحم يتحكم فيه شرطي مرور تتعارض إشاراته مع إشارات المرور الضوئية، يجب عليك:",
           options=["اتباع الإشارة الضوئية لأنها تلقائية وصحيحة دائماً","اتباع توجيهات الشرطي، والتي تكون لها الأولوية على الإشارة الضوئية","التوقف التام والانتظار حتى تتفق الإشارتان","اتباع ما هو أكثر ملاءمة لاتجاهك"],
           explanation="توجيهات شرطي المرور لها الأولوية على الإشارات الضوئية واللافتات لأن الشرطي يمكنه التعامل مع ظروف لحظية لا تستطيع الإشارة الآلية إدراكها."),
   answer=1),
 dict(id="ri_004", difficulty=1,
   en=dict(q="When approaching a roundabout, indicating your exit is:",
           options=["Not necessary since roundabouts are self-explanatory","Good practice - signal left just before your exit to inform other drivers","Only required for the first exit","Only required for trucks"],
           explanation="Signalling your exit direction (typically left, just before leaving) helps other drivers and pedestrians anticipate your movement and improves safety."),
   ar=dict(q="عند الاقتراب من دوار، الإشارة إلى مخرجك تُعد:",
           options=["غير ضرورية لأن الدوارات واضحة بذاتها","ممارسة جيدة - استخدم إشارة اليسار قبل مخرجك مباشرة لإعلام السائقين الآخرين","مطلوبة فقط للمخرج الأول","مطلوبة فقط للشاحنات"],
           explanation="الإشارة إلى اتجاه الخروج (عادة يساراً قبيل المخرج) تساعد السائقين والمشاة الآخرين على توقع حركتك."),
   answer=1),
],
"parking_rules": [
 dict(id="pk_001", difficulty=1,
   en=dict(q="Parking in a spot marked with yellow/hatched lines or a 'No Parking' sign is:",
           options=["Allowed for less than 5 minutes","Not allowed at any time unless otherwise indicated","Allowed only for residents","Allowed on Fridays"],
           explanation="Marked no-parking zones (yellow lines, hatching, or explicit signs) prohibit parking at all times unless a specific exception is posted; a brief stop does not exempt a driver from the rule in a strict no-parking zone."),
   ar=dict(q="الوقوف في مكان مُعلَّم بخطوط صفراء/متقاطعة أو لافتة 'ممنوع الوقوف' يُعد:",
           options=["مسموحاً لأقل من 5 دقائق","غير مسموح في أي وقت ما لم يُذكر خلاف ذلك","مسموحاً للمقيمين فقط","مسموحاً أيام الجمعة"],
           explanation="مناطق منع الوقوف المعلّمة تمنع الوقوف في كل الأوقات ما لم يُذكر استثناء محدد."),
   answer=1),
 dict(id="pk_002", difficulty=1,
   en=dict(q="Paid public parking zones in most UAE cities generally require payment:",
           options=["Only on weekends","During specified hours on specified days, typically via an app, SMS, or meter","Only for vehicles with foreign plates","Only at night"],
           explanation="Public paid parking (e.g. RTA parking in Dubai) applies during designated hours on working days and is usually paid via app, SMS, or parking meter; timing/fee details vary by emirate and zone.",
           ),
   ar=dict(q="مناطق الوقوف العامة المدفوعة في معظم مدن الإمارات تتطلب عموماً الدفع:",
           options=["أيام نهاية الأسبوع فقط","خلال ساعات محددة في أيام محددة، عادة عبر تطبيق أو رسالة نصية أو عداد","للمركبات ذات اللوحات الأجنبية فقط","ليلاً فقط"],
           explanation="الوقوف العام المدفوع (مثل مواقف هيئة الطرق والمواصلات في دبي) يُطبق خلال ساعات محددة في أيام العمل، ويُدفع عادة عبر تطبيق أو رسالة نصية أو عداد؛ التفاصيل تختلف حسب الإمارة والمنطقة."),
   answer=1, needsVerification=True),
 dict(id="pk_003", difficulty=1,
   en=dict(q="Parking in a space reserved for People of Determination (disabled parking) without a valid permit is:",
           options=["Allowed for a quick errand","A violation that carries a fine even for a short stop","Allowed if no one else needs it at that moment","Only enforced in shopping malls"],
           explanation="Reserved accessible parking spaces are protected by law regardless of how briefly a non-permit holder intends to park there."),
   ar=dict(q="الوقوف في مكان مخصص لأصحاب الهمم دون تصريح صالح يُعد:",
           options=["مسموحاً لقضاء مشوار سريع","مخالفة تستوجب غرامة حتى لو كان التوقف قصيراً","مسموحاً إذا لم يكن أحد بحاجته في تلك اللحظة","يُطبق فقط في مراكز التسوق"],
           explanation="مواقف أصحاب الهمم محمية بالقانون بغض النظر عن قصر مدة الوقوف من قبل غير الحاصلين على تصريح."),
   answer=1),
 dict(id="pk_004", difficulty=1,
   en=dict(q="Double-parking (stopping alongside an already parked vehicle, blocking a lane) is:",
           options=["Fine as long as your hazard lights are on","A violation because it obstructs traffic flow and can cause accidents","Only a problem in narrow streets","Allowed for less than 2 minutes"],
           explanation="Double-parking blocks a traffic lane and creates a hazard for other road users; it is treated as a violation regardless of hazard lights or short duration."),
   ar=dict(q="الوقوف المزدوج (التوقف بجانب مركبة متوقفة بالفعل وسد المسار) يُعد:",
           options=["مقبولاً طالما أضواء التحذير مضاءة","مخالفة لأنه يعيق تدفق حركة المرور ويمكن أن يسبب حوادث","مشكلة فقط في الشوارع الضيقة","مسموحاً لأقل من دقيقتين"],
           explanation="الوقوف المزدوج يسد مسار حركة المرور ويشكل خطراً على مستخدمي الطريق الآخرين، ويُعد مخالفة بغض النظر عن أضواء التحذير أو قصر المدة."),
   answer=1),
],
"seatbelt_child_safety": [
 dict(id="sb_001", difficulty=1,
   en=dict(q="In the UAE, seatbelts are legally required for:",
           options=["The driver only","The driver and front passenger only","All occupants of the vehicle, front and rear seats","Only on highways"],
           explanation="UAE traffic law requires all occupants, both front and rear seats, to wear seatbelts while the vehicle is moving."),
   ar=dict(q="في الإمارات، يُشترط قانونياً ربط حزام الأمان لـ:",
           options=["السائق فقط","السائق والراكب الأمامي فقط","جميع ركاب المركبة، الأمامي والخلفي","على الطرق السريعة فقط"],
           explanation="يشترط القانون المروري في الإمارات ربط جميع الركاب لحزام الأمان، في المقاعد الأمامية والخلفية، أثناء سير المركبة."),
   answer=2),
 dict(id="sb_002", difficulty=1,
   en=dict(q="Young children below a certain age/height in the UAE are required to:",
           options=["Sit on an adult's lap for safety","Be secured in an appropriate child car seat suited to their age/size","Sit in the front seat for better visibility","Wear only a regular adult seatbelt from age 2"],
           explanation="UAE law requires young children to be secured in a suitable child car seat rather than held on a lap or restrained only by an adult seatbelt not sized for them; the exact age/height thresholds should be checked against the current official rule.",
           ),
   ar=dict(q="يُشترط للأطفال الصغار دون سن/طول معين في الإمارات:",
           options=["الجلوس في حضن أحد الكبار للأمان","تثبيتهم في مقعد سيارة مخصص للأطفال يناسب عمرهم/حجمهم","الجلوس في المقعد الأمامي لرؤية أفضل","استخدام حزام أمان الكبار العادي فقط بدءاً من عمر سنتين"],
           explanation="يشترط القانون في الإمارات تثبيت الأطفال الصغار في مقعد سيارة مخصص للأطفال؛ يجب التحقق من حدود العمر/الطول الدقيقة من القاعدة الرسمية الحالية."),
   answer=1, needsVerification=True),
 dict(id="sb_003", difficulty=1,
   en=dict(q="Not wearing a seatbelt while driving or riding in a UAE vehicle is:",
           options=["Not an offence if the trip is short","A traffic violation that carries a fine","Only checked for drivers, never for passengers","Optional on quiet roads"],
           explanation="Failing to wear a seatbelt is an enforced traffic offence in the UAE for drivers and passengers alike, regardless of trip length or road type."),
   ar=dict(q="عدم ربط حزام الأمان أثناء القيادة أو ركوب مركبة في الإمارات يُعد:",
           options=["ليس مخالفة إذا كانت الرحلة قصيرة","مخالفة مرورية تستوجب غرامة","تُفحص للسائقين فقط وليس للركاب","اختيارياً في الطرق الهادئة"],
           explanation="عدم ربط حزام الأمان مخالفة مرورية يُعاقب عليها في الإمارات للسائقين والركاب على حد سواء."),
   answer=1),
 dict(id="sb_004", difficulty=2,
   en=dict(q="A rear-facing child car seat is most appropriate for:",
           options=["Teenagers","Infants and very young children, per the seat manufacturer's size/age guidance","Adults with back pain","Any passenger sitting in the rear"],
           explanation="Rear-facing seats are designed for infants and very young children because they better protect the head, neck, and spine in a frontal collision at that stage of development."),
   ar=dict(q="مقعد الطفل المواجه للخلف هو الأنسب لـ:",
           options=["المراهقين","الرضع والأطفال الصغار جداً وفق إرشادات الشركة المصنعة للحجم/العمر","الكبار الذين يعانون آلام الظهر","أي راكب يجلس في المقعد الخلفي"],
           explanation="المقاعد المواجهة للخلف مصممة للرضع والأطفال الصغار جداً لأنها تحمي الرأس والرقبة والعمود الفقري بشكل أفضل في حال الاصطدام الأمامي."),
   answer=1),
],
"alcohol_fatigue": [
 dict(id="af_001", difficulty=1,
   en=dict(q="The legal alcohol limit for driving in the UAE is best described as:",
           options=["The same lenient limits as some other countries, some alcohol is allowed","Effectively a zero-tolerance approach - driving with any detectable alcohol is treated very seriously","No rule exists for residents, only for tourists","Only enforced during Ramadan"],
           explanation="The UAE takes a very strict, near zero-tolerance stance on drink-driving; even small amounts of alcohol can lead to serious penalties. Exact legal blood-alcohol thresholds and penalties can change and should be confirmed against the current official law.",
           ),
   ar=dict(q="يُوصف الحد القانوني للكحول أثناء القيادة في الإمارات بأنه:",
           options=["حدود متساهلة مشابهة لبعض الدول الأخرى، يُسمح بكمية بسيطة من الكحول","نهج شبه صارم بعدم التسامح إطلاقاً - القيادة بأي أثر كحول يُعامل بجدية بالغة","لا توجد قاعدة للمقيمين، فقط للسياح","يُطبق فقط خلال شهر رمضان"],
           explanation="تتبنى الإمارات نهجاً صارماً جداً وشبه صفري تجاه القيادة تحت تأثير الكحول؛ يجب التحقق من الحدود والعقوبات الدقيقة من القانون الرسمي الحالي."),
   answer=1, needsVerification=True),
 dict(id="af_002", difficulty=1,
   en=dict(q="If you feel drowsy or fatigued during a long drive, you should:",
           options=["Open the window and continue driving at the same speed","Turn up the music and push through fatigue","Stop at a safe place to rest before continuing","Drive faster to reach your destination sooner and rest there"],
           explanation="Fatigue significantly slows reaction time similar to alcohol impairment; the safe response is to stop and rest, not to try to power through with temporary distractions."),
   ar=dict(q="إذا شعرت بالنعاس أو التعب أثناء رحلة طويلة، يجب عليك:",
           options=["فتح النافذة ومتابعة القيادة بنفس السرعة","رفع صوت الموسيقى ومتابعة القيادة رغم التعب","التوقف في مكان آمن للراحة قبل المتابعة","القيادة بسرعة أكبر للوصول أسرع والراحة هناك"],
           explanation="التعب يبطئ وقت رد الفعل بشكل كبير مشابه لتأثير الكحول؛ الاستجابة الآمنة هي التوقف والراحة."),
   answer=2),
 dict(id="af_003", difficulty=2,
   en=dict(q="Driving under the influence of certain prescription or over-the-counter medications that cause drowsiness is:",
           options=["Always fine since the medication is legal","Potentially dangerous and can be treated as impaired driving if it affects your ability to drive safely","Only a concern for commercial drivers","Not regulated at all"],
           explanation="Impairment can come from legal medication as well as alcohol or illegal substances; if a medication affects alertness or reaction time, driving under its influence can be treated as a form of impaired/unsafe driving."),
   ar=dict(q="القيادة تحت تأثير بعض الأدوية الموصوفة أو المتاحة دون وصفة والتي تسبب النعاس تُعد:",
           options=["مقبولة دائماً لأن الدواء قانوني","خطيرة محتملة ويمكن اعتبارها قيادة تحت تأثير مُعيق إذا أثرت على القدرة على القيادة بأمان","تهم السائقين التجاريين فقط","غير منظمة إطلاقاً"],
           explanation="يمكن أن ينشأ الإعاقة عن أدوية قانونية وليس فقط عن الكحول أو المواد الممنوعة؛ إذا أثر الدواء على اليقظة أو رد الفعل فقد تُعامل القيادة تحت تأثيره كقيادة غير آمنة."),
   answer=1),
 dict(id="af_004", difficulty=1,
   en=dict(q="On a long inter-emirate drive, it is recommended to take a rest break approximately every:",
           options=["30 minutes","2 hours, or sooner if you feel tired","6 hours","Only when you run out of fuel"],
           explanation="Taking a short break roughly every two hours (or sooner if fatigue sets in earlier) helps maintain alertness on long drives; exact recommended intervals can vary by guidance source."),
   ar=dict(q="في رحلة طويلة بين الإمارات، يُنصح بأخذ استراحة تقريباً كل:",
           options=["30 دقيقة","ساعتين، أو أبكر إذا شعرت بالتعب","6 ساعات","فقط عند نفاد الوقود"],
           explanation="أخذ استراحة قصيرة كل ساعتين تقريباً (أو أبكر عند الشعور بالتعب) يساعد في الحفاظ على اليقظة أثناء الرحلات الطويلة."),
   answer=1, needsVerification=True),
 dict(id="af_005", difficulty=1,
   en=dict(q="Using recreational drugs before driving is:",
           options=["Acceptable as long as you feel fine","Strictly prohibited and treated as a serious offence, even stricter than alcohol in UAE law","Only a problem for professional drivers","Allowed in small amounts"],
           explanation="The UAE enforces very strict laws against driving under the influence of narcotics or controlled substances, with severe penalties even for trace amounts; exact legal thresholds should be confirmed against current law.",
           ),
   ar=dict(q="تعاطي المخدرات الترفيهية قبل القيادة يُعد:",
           options=["مقبولاً طالما تشعر أنك بخير","ممنوعاً منعاً باتاً ويُعامل كجريمة خطيرة، وأشد صرامة من الكحول في القانون الإماراتي","مشكلة للسائقين المحترفين فقط","مسموحاً بكميات صغيرة"],
           explanation="تُطبق الإمارات قوانين صارمة جداً ضد القيادة تحت تأثير المخدرات أو المؤثرات العقلية، مع عقوبات شديدة حتى لآثار ضئيلة."),
   answer=1, needsVerification=True),
],
"vehicle_docs_insurance": [
 dict(id="vd_001", difficulty=1,
   en=dict(q="Driving a vehicle in the UAE without valid registration (Mulkiya) is:",
           options=["Allowed within the same emirate only","A traffic violation regardless of which emirate you are in","Allowed for the first month after purchase only","Only checked at border crossings"],
           explanation="A vehicle must carry valid registration (Mulkiya) at all times; driving without it, or with an expired one, is a traffic violation anywhere in the UAE."),
   ar=dict(q="قيادة مركبة في الإمارات بدون تسجيل ساري (الملكية) يُعد:",
           options=["مسموحاً داخل نفس الإمارة فقط","مخالفة مرورية بغض النظر عن الإمارة التي تكون فيها","مسموحاً خلال الشهر الأول بعد الشراء فقط","يُفحص فقط عند المعابر الحدودية"],
           explanation="يجب أن تحمل المركبة تسجيلاً سارياً (الملكية) في كل الأوقات؛ القيادة بدونه أو بتسجيل منتهي مخالفة مرورية في أي إمارة."),
   answer=1),
 dict(id="vd_002", difficulty=1,
   en=dict(q="Third-party motor insurance in the UAE typically covers:",
           options=["Damage to your own vehicle only","Injury or damage caused to other people/vehicles, not your own vehicle's damage","Nothing, insurance is optional and rarely used","Only theft of your own vehicle"],
           explanation="Third-party insurance covers liability for injury or damage you cause to others; it does not cover repairs to your own vehicle, which requires comprehensive cover."),
   ar=dict(q="يشمل تأمين المركبات ضد الغير في الإمارات عادة:",
           options=["أضرار مركبتك الخاصة فقط","الإصابات أو الأضرار التي تلحق بالآخرين/مركباتهم وليس مركبتك","لا شيء، فالتأمين اختياري ونادراً ما يُستخدم","سرقة مركبتك فقط"],
           explanation="يغطي تأمين الطرف الثالث المسؤولية عن الإصابات أو الأضرار التي تسببها للآخرين، ولا يغطي إصلاح مركبتك الخاصة."),
   answer=1),
 dict(id="vd_003", difficulty=1,
   en=dict(q="If you are involved in a minor accident with no injuries and both parties agree on what happened, you should generally:",
           options=["Leave the scene immediately without informing anyone","Use the appropriate accident reporting process (e.g. a police-approved app or reporting centre) to document it properly","Only exchange phone numbers and do nothing else","Never involve the police under any circumstances"],
           explanation="Even for minor accidents, UAE traffic authorities provide a formal process (in Dubai, for example, via a dedicated police reporting app for minor accidents) to document the incident properly for insurance purposes; leaving the scene without reporting can itself be a violation.",
           ),
   ar=dict(q="إذا تعرضت لحادث بسيط دون إصابات واتفق الطرفان على ما حدث، يجب عليك عموماً:",
           options=["مغادرة الموقع فوراً دون إبلاغ أي جهة","استخدام إجراء الإبلاغ عن الحوادث المناسب (مثل تطبيق شرطي معتمد أو مركز إبلاغ) لتوثيق الحادث بشكل صحيح","تبادل أرقام الهواتف فقط دون أي إجراء آخر","عدم إشراك الشرطة إطلاقاً تحت أي ظرف"],
           explanation="حتى في الحوادث البسيطة، توفر الجهات المرورية في الإمارات إجراءً رسمياً لتوثيق الحادث لأغراض التأمين؛ مغادرة الموقع دون إبلاغ يمكن أن تكون مخالفة بحد ذاتها."),
   answer=1, needsVerification=True),
 dict(id="vd_004", difficulty=2,
   en=dict(q="A UAE driving licence obtained in one emirate is:",
           options=["Valid to drive in that emirate only","Valid across all seven emirates","Valid only for one year regardless of the printed expiry","Valid only for UAE nationals"],
           explanation="A UAE driving licence issued by any emirate's traffic authority is valid for driving across the whole country, not just the issuing emirate."),
   ar=dict(q="رخصة القيادة الإماراتية الصادرة من إمارة معينة تكون:",
           options=["سارية للقيادة في تلك الإمارة فقط","سارية في جميع الإمارات السبع","سارية لمدة سنة واحدة فقط بغض النظر عن تاريخ الانتهاء المطبوع","سارية لمواطني الإمارات فقط"],
           explanation="رخصة القيادة الإماراتية الصادرة من أي إمارة تكون سارية للقيادة في جميع أنحاء الدولة."),
   answer=1),
 dict(id="vd_005", difficulty=1,
   en=dict(q="A visitor driving in the UAE on an International Driving Permit (IDP) together with their national licence is generally:",
           options=["Never allowed to drive","Allowed to drive for a limited period as a visitor, subject to current rules for their home country","Required to retake the full UAE test immediately","Only allowed to drive rental cars from one specific company"],
           explanation="Many visitors can drive temporarily in the UAE using an International Driving Permit alongside their national licence, though exact eligibility depends on the visitor's home country and current regulations, so this should be checked before travel.",
           ),
   ar=dict(q="الزائر الذي يقود في الإمارات برخصة قيادة دولية (IDP) مع رخصته الوطنية يكون عموماً:",
           options=["غير مسموح له بالقيادة إطلاقاً","مسموحاً له بالقيادة لفترة محدودة كزائر وفق القواعد الحالية لبلده","مطالباً بإعادة اختبار القيادة الإماراتي الكامل فوراً","مسموحاً له فقط بقيادة سيارات مؤجرة من شركة واحدة محددة"],
           explanation="يمكن للعديد من الزوار القيادة مؤقتاً في الإمارات برخصة دولية مع رخصتهم الوطنية، لكن الأهلية الدقيقة تعتمد على بلد الزائر والأنظمة الحالية."),
   answer=1, needsVerification=True),
 dict(id="vd_006", difficulty=1,
   en=dict(q="Vehicle registration (Mulkiya) in the UAE typically needs to be renewed:",
           options=["Never, it is valid for the vehicle's lifetime","Periodically (commonly annually or biennially, depending on vehicle age/type), along with a passing inspection","Only when selling the vehicle","Only if the vehicle is involved in an accident"],
           explanation="UAE vehicle registration must be renewed periodically, generally requiring a roadworthiness/inspection test first; exact renewal periods can depend on vehicle age and emirate, so should be checked against current RTA/traffic authority rules.",
           ),
   ar=dict(q="يحتاج تسجيل المركبة (الملكية) في الإمارات عادة إلى التجديد:",
           options=["أبداً، فهو ساري طوال عمر المركبة","بشكل دوري (سنوياً أو كل سنتين عادة، حسب عمر/نوع المركبة) مع اجتياز فحص الفحص الفني","فقط عند بيع المركبة","فقط إذا تعرضت المركبة لحادث"],
           explanation="يجب تجديد تسجيل المركبة في الإمارات بشكل دوري، ويتطلب عادة اجتياز فحص فني أولاً؛ يجب التحقق من الفترة الدقيقة من الجهة المرورية الرسمية."),
   answer=1, needsVerification=True),
],
}

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    total = 0
    for category, questions in BANK.items():
        for q in questions:
            q.setdefault("needsVerification", False)
            q["category"] = category
        path = os.path.join(OUT_DIR, f"{category}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"category": category, "questions": questions}, f, ensure_ascii=False, indent=2)
        total += len(questions)
        print(f"wrote {len(questions):2d} questions -> {path}")
    print(f"TOTAL questions authored: {total}")

if __name__ == "__main__":
    main()
